kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-manager-binding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "nostr-broadcaster-k8s-server.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: jobs-role
  apiGroup: rbac.authorization.k8s.io